# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-12 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='experiment_number',
            field=models.IntegerField(blank=True, default=0, help_text='HFIR Experiment Number (expXXX)', null=True),
        ),
    ]
