# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 18:09
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='experiment',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(code='invalid_exp', message='Exp must be of the form: expXXX', regex='^exp\\d+$')], verbose_name='Experiment (Only used at HFIR!)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='ipts',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(code='invalid_ipts', message='IPTS must be of the form: IPTS-XXXX', regex='^IPTS-\\d+$')], verbose_name='Integrated Proposal Tracking System (IPTS)'),
        ),
    ]
