# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-18 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='experiment',
            field=models.CharField(blank=True, max_length=20, verbose_name='Experiment (Only used at HFIR!)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='ipts',
            field=models.CharField(blank=True, max_length=20, verbose_name='Integrated Proposal Tracking System (IPTS)'),
        ),
    ]
