# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-14 22:14
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='instrument',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='facility', chained_model_field='facility', on_delete=django.db.models.deletion.CASCADE, to='catalog.Instrument'),
        ),
    ]
