# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-12 18:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170512_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='experiment_number',
            field=models.IntegerField(blank=True, help_text='HFIR Experiment Number (expXXX)', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='experiment_number',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='ipts', chained_model_field='ipts', null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Experiment'),
        ),
    ]
