# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-12 19:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20170512_1442'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='experiment_number',
            new_name='experiment',
        ),
    ]
