# Generated by Django 2.0.4 on 2018-05-16 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reduction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reductionhyspec',
            name='ub_a',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='a'),
        ),
        migrations.AlterField(
            model_name='reductionhyspec',
            name='ub_alpha',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='\\(\t\\alpha \\)'),
        ),
        migrations.AlterField(
            model_name='reductionhyspec',
            name='ub_b',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='b'),
        ),
        migrations.AlterField(
            model_name='reductionhyspec',
            name='ub_beta',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='\\(\t\\beta \\)'),
        ),
        migrations.AlterField(
            model_name='reductionhyspec',
            name='ub_c',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='c'),
        ),
        migrations.AlterField(
            model_name='reductionhyspec',
            name='ub_gamma',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='\\(\t\\gamma \\)'),
        ),
    ]
