# Generated by Django 2.0.5 on 2018-06-07 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reduction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reductionhyspec',
            name='e_i',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Nominal \\( E_{i} \\).', max_digits=4, null=True, verbose_name='\\( E_{i} \\)'),
        ),
    ]
