# Generated by Django 2.0.3 on 2018-03-12 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reduction', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sanshfirbiosansregion',
            options={},
        ),
        migrations.AlterModelOptions(
            name='sanshfirgpsansregion',
            options={},
        ),
    ]
