# Generated by Django 2.0.4 on 2018-05-21 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reduction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reductionbiosans',
            name='year_in_school',
            field=models.IntegerField(choices=[(1, 'Copy script and execute'), (2, 'Copy script'), (3, 'Copy script to autoreduction')], default=1),
        ),
        migrations.AddField(
            model_name='reductiongpsans',
            name='year_in_school',
            field=models.IntegerField(choices=[(1, 'Copy script and execute'), (2, 'Copy script'), (3, 'Copy script to autoreduction')], default=1),
        ),
        migrations.AddField(
            model_name='reductionhyspec',
            name='year_in_school',
            field=models.IntegerField(choices=[(1, 'Copy script and execute'), (2, 'Copy script'), (3, 'Copy script to autoreduction')], default=1),
        ),
    ]
