# Generated by Django 2.0.4 on 2018-05-21 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reduction', '0002_auto_20180521_1702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reductionbiosans',
            name='year_in_school',
        ),
        migrations.RemoveField(
            model_name='reductiongpsans',
            name='year_in_school',
        ),
        migrations.RemoveField(
            model_name='reductionhyspec',
            name='year_in_school',
        ),
        migrations.AddField(
            model_name='reductionbiosans',
            name='run_type',
            field=models.IntegerField(choices=[(1, 'Copy script and execute'), (2, 'Copy script'), (3, 'Copy script to autoreduction')], default=1, help_text='For auto reduction copy only the script. If you have previledges you can copy the script to autoreduction.'),
        ),
        migrations.AddField(
            model_name='reductiongpsans',
            name='run_type',
            field=models.IntegerField(choices=[(1, 'Copy script and execute'), (2, 'Copy script'), (3, 'Copy script to autoreduction')], default=1, help_text='For auto reduction copy only the script. If you have previledges you can copy the script to autoreduction.'),
        ),
        migrations.AddField(
            model_name='reductionhyspec',
            name='run_type',
            field=models.IntegerField(choices=[(1, 'Copy script and execute'), (2, 'Copy script'), (3, 'Copy script to autoreduction')], default=1, help_text='For auto reduction copy only the script. If you have previledges you can copy the script to autoreduction.'),
        ),
    ]
