# Generated by Django 2.0.3 on 2018-03-13 18:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import server.apps.reduction.models.abstract


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('configuration', '0005_sanshfirbiosansconfiguration_sanshfirgpsansconfiguration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('django_remote_submission', '0001_initial'),
        ('reduction', '0002_auto_20180312_1824'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpectrometrySnsHyspecReduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('script_execution_path', models.CharField(max_length=256)),
                ('script', models.TextField(blank=True, help_text='Python script generated from the reduction entry.         If the script was generated already just shows it!')),
                ('field3', models.CharField(blank=True, help_text='Help for the field.', max_length=128, verbose_name='Human description 3')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spectrometrysnshyspecreduction_instruments', related_query_name='spectrometrysnshyspecreduction_instrument', to='catalog.Instrument')),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spectrometrysnshyspecreduction_job', related_query_name='spectrometrysnshyspecreduction_job', to='django_remote_submission.Job')),
                ('script_interpreter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spectrometrysnshyspecreduction_interpreters', related_query_name='spectrometrysnshyspecreduction_interpreter', to='django_remote_submission.Interpreter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spectrometrysnshyspecreduction_users', related_query_name='spectrometrysnshyspecreduction_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
            bases=(models.Model, server.apps.reduction.models.abstract.ModelMixin),
        ),
        migrations.CreateModel(
            name='SpectrometrySnsHyspecRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('comments', models.CharField(blank=True, help_text='Any necessary comments...', max_length=256)),
                ('field1', models.CharField(blank=True, help_text='Help fr the field.', max_length=128, verbose_name='Human description 1')),
                ('field2', models.CharField(blank=True, help_text='Help fr the field.', max_length=128, verbose_name='Human description 2')),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regions', related_query_name='region', to='configuration.SpectrometrySnsHyspecConfiguration')),
                ('reduction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regions', related_query_name='region', to='reduction.SpectrometrySnsHyspecReduction')),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
            bases=(models.Model, server.apps.reduction.models.abstract.ModelMixin),
        ),
    ]
