# Generated by Django 2.0.5 on 2018-06-05 10:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reduction', '0002_reductionhyspec_e_i'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reductionbiosans',
            name='user',
        ),
        migrations.RemoveField(
            model_name='reductiongpsans',
            name='user',
        ),
        migrations.RemoveField(
            model_name='reductionhyspec',
            name='user',
        ),
        migrations.AddField(
            model_name='reductionbiosans',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reductiongpsans',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reductionhyspec',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
