# Generated by Django 2.0.3 on 2018-03-13 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0005_sanshfirbiosansconfiguration_sanshfirgpsansconfiguration'),
        ('reduction', '0003_spectrometrysnshyspecreduction_spectrometrysnshyspecregion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spectrometrysnshyspecregion',
            name='configuration',
        ),
        migrations.AddField(
            model_name='spectrometrysnshyspecreduction',
            name='configuration',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='regions', related_query_name='region', to='configuration.SpectrometrySnsHyspecConfiguration'),
            preserve_default=False,
        ),
    ]
