# Generated by Django 2.0.4 on 2018-05-21 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reduction', '0003_auto_20180521_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reductionbiosans',
            name='script_interpreter',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reductionbiosans_interpreters', related_query_name='reductionbiosans_interpreter', to='django_remote_submission.Interpreter'),
        ),
        migrations.AlterField(
            model_name='reductiongpsans',
            name='script_interpreter',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reductiongpsans_interpreters', related_query_name='reductiongpsans_interpreter', to='django_remote_submission.Interpreter'),
        ),
        migrations.AlterField(
            model_name='reductionhyspec',
            name='script_interpreter',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reductionhyspec_interpreters', related_query_name='reductionhyspec_interpreter', to='django_remote_submission.Interpreter'),
        ),
    ]
