# Generated by Django 2.0.5 on 2018-06-06 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reduction', '0003_auto_20180605_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reductionbiosans',
            name='share_with_ipts',
            field=models.BooleanField(default=True, help_text='If checked, anyone belonging to this IPTS can see and change this Redution.', verbose_name='Share this reduction with other members of this IPTS.'),
        ),
        migrations.AlterField(
            model_name='reductiongpsans',
            name='share_with_ipts',
            field=models.BooleanField(default=True, help_text='If checked, anyone belonging to this IPTS can see and change this Redution.', verbose_name='Share this reduction with other members of this IPTS.'),
        ),
        migrations.AlterField(
            model_name='reductionhyspec',
            name='share_with_ipts',
            field=models.BooleanField(default=True, help_text='If checked, anyone belonging to this IPTS can see and change this Redution.', verbose_name='Share this reduction with other members of this IPTS.'),
        ),
    ]
