# Generated by Django 2.0.5 on 2018-07-04 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reduction', '0004_auto_20180605_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reductionbiosans',
            name='share_with_ipts',
        ),
        migrations.RemoveField(
            model_name='reductiongpsans',
            name='share_with_ipts',
        ),
        migrations.RemoveField(
            model_name='reductionhyspec',
            name='share_with_ipts',
        ),
    ]
