# Generated by Django 2.0.5 on 2018-07-07 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('django_remote_submission', '0001_initial'),
        ('reduction', '0005_auto_20180704_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=256)),
                ('script_template_path', models.CharField(help_text='Where the script template is. E.g. /SNS/HYS/shared/templates/reduce.tpl', max_length=256)),
                ('destination_directory_path_template', models.CharField(help_text='Where the script is going to be copied and may be executed. E.g. /SNS/HYS/%(ipts_number)s/shared/reduce/%(hash)s', max_length=256)),
                ('django_remote_submission_tasks', models.CharField(help_text='Tasks in Django Remote Submission: copy_job_to_server, submit_job_to_server', max_length=32)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions_instruments', related_query_name='actions_instrument', to='catalog.Instrument')),
                ('script_interpreter', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions_interpreters', related_query_name='actions_interpreter', to='django_remote_submission.Interpreter')),
            ],
        ),
        migrations.RemoveField(
            model_name='reductionbiosans',
            name='run_type',
        ),
        migrations.RemoveField(
            model_name='reductionbiosans',
            name='script_execution_path',
        ),
        migrations.RemoveField(
            model_name='reductionbiosans',
            name='script_interpreter',
        ),
        migrations.RemoveField(
            model_name='reductiongpsans',
            name='run_type',
        ),
        migrations.RemoveField(
            model_name='reductiongpsans',
            name='script_execution_path',
        ),
        migrations.RemoveField(
            model_name='reductiongpsans',
            name='script_interpreter',
        ),
        migrations.RemoveField(
            model_name='reductionhyspec',
            name='run_type',
        ),
        migrations.RemoveField(
            model_name='reductionhyspec',
            name='script_execution_path',
        ),
        migrations.RemoveField(
            model_name='reductionhyspec',
            name='script_interpreter',
        ),
    ]
