# Generated by Django 2.0.5 on 2018-07-07 17:21

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reduction', '0007_auto_20180707_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='reductionbiosans',
            name='parameters',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='reductiongpsans',
            name='parameters',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='reductionhyspec',
            name='parameters',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
