# Generated by Django 2.0.5 on 2018-07-13 16:36

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reduction', '0008_auto_20180707_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actions',
            name='script_interpreter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions_interpreters', related_query_name='actions_interpreter', to='django_remote_submission.Interpreter'),
        ),
        migrations.AlterField(
            model_name='reductionbiosans',
            name='parameters',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=[], null=True),
        ),
        migrations.AlterField(
            model_name='reductiongpsans',
            name='parameters',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=[], null=True),
        ),
        migrations.AlterField(
            model_name='reductionhyspec',
            name='parameters',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=[], null=True),
        ),
    ]
