# Generated by Django 2.0.5 on 2018-07-16 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reduction', '0009_auto_20180713_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reductionbiosans',
            name='action',
            field=models.ForeignKey(help_text='Pick an action for your reduction', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reductionbiosans_action', related_query_name='reductionbiosans_action', to='reduction.Actions', verbose_name='Action to take for the reduction'),
        ),
        migrations.AlterField(
            model_name='reductiongpsans',
            name='action',
            field=models.ForeignKey(help_text='Pick an action for your reduction', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reductiongpsans_action', related_query_name='reductiongpsans_action', to='reduction.Actions', verbose_name='Action to take for the reduction'),
        ),
        migrations.AlterField(
            model_name='reductionhyspec',
            name='action',
            field=models.ForeignKey(help_text='Pick an action for your reduction', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reductionhyspec_action', related_query_name='reductionhyspec_action', to='reduction.Actions', verbose_name='Action to take for the reduction'),
        ),
    ]
