# Generated by Django 2.0.5 on 2018-07-23 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reduction', '0010_auto_20180716_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reductionhyspec',
            name='ub_alpha',
            field=models.DecimalField(decimal_places=4, default=90.0, help_text='alpha', max_digits=8, null=True, verbose_name='\\(\t\\alpha \\)'),
        ),
        migrations.AlterField(
            model_name='reductionhyspec',
            name='ub_beta',
            field=models.DecimalField(decimal_places=4, default=90.0, help_text='beta', max_digits=8, null=True, verbose_name='\\(\t\\beta \\)'),
        ),
        migrations.AlterField(
            model_name='reductionhyspec',
            name='ub_gamma',
            field=models.DecimalField(decimal_places=4, default=90.0, help_text='gamma', max_digits=8, null=True, verbose_name='\\(\t\\gamma \\)'),
        ),
    ]
