# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 11:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sans', '0003_auto_20161229_0553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biosansregion',
            name='configuration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regions', related_query_name='region', to='sans.BioSANSConfiguration'),
        ),
    ]
