# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-22 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='biosansconfiguration',
            name='beam_center_file',
            field=models.CharField(blank=True, help_text='Note that the user can always overwrite this value!', max_length=64, verbose_name='Beam Center file'),
        ),
        migrations.AddField(
            model_name='biosansconfiguration',
            name='empty_beam_file',
            field=models.CharField(blank=True, help_text='Note that the user can always overwrite this value!', max_length=64, verbose_name='Empty Beam Transmission file'),
        ),
    ]
