# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-09 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sans', '0002_auto_20170105_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='biosansreduction',
            name='script',
            field=models.TextField(blank=True, help_text='Python script generated from the reduction entry.'),
        ),
        migrations.AddField(
            model_name='gpsansconfiguration',
            name='wavelength',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='If empty uses the value set in the data file.', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='gpsansreduction',
            name='script',
            field=models.TextField(blank=True, help_text='Python script generated from the reduction entry.'),
        ),
    ]
