# Generated by Django 2.0.2 on 2018-02-23 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sans', '0002_auto_20180221_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='biosansregion',
            name='stitch',
            field=models.BooleanField(default=True, help_text='The rows with the same index will be stitched together to produce a single I(q)', verbose_name='Stitch Q Ranges'),
        ),
        migrations.AddField(
            model_name='gpsansregion',
            name='stitch',
            field=models.BooleanField(default=True, help_text='The rows with the same index will be stitched together to produce a single I(q)', verbose_name='Stitch Q Ranges'),
        ),
    ]
