# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-27 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sans', '0002_auto_20170329_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='biosansreduction',
            name='script_execution_path',
            field=models.CharField(default="", max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gpsansreduction',
            name='script_execution_path',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
