# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-22 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sans', '0002_auto_20170522_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biosansregion',
            name='beam_center_run',
            field=models.CharField(blank=True, help_text='Use run number or file path. If empty, uses that of the Configuration.', max_length=128, verbose_name='Beam Center'),
        ),
        migrations.AlterField(
            model_name='biosansregion',
            name='empty_beam_run',
            field=models.CharField(blank=True, help_text='Use run number or file path. If empty, uses that of the Configuration.', max_length=128, verbose_name='Empty Beam Transmission'),
        ),
        migrations.AlterField(
            model_name='gpsansregion',
            name='beam_center_run',
            field=models.CharField(blank=True, help_text='Use run number or file path. If empty, uses that of the Configuration.', max_length=128, verbose_name='Beam Center'),
        ),
        migrations.AlterField(
            model_name='gpsansregion',
            name='empty_beam_run',
            field=models.CharField(blank=True, help_text='Use run number or file path. If empty, uses that of the Configuration.', max_length=128, verbose_name='Empty Beam Transmission'),
        ),
    ]
