# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-09 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sans', '0003_auto_20170109_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpsansconfiguration',
            name='sample_detector_distance',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='(in meters) If empty uses the value set in the data file.', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='gpsansconfiguration',
            name='wavelength_spread',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='If empty uses the value set in the data file.', max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='gpsansconfiguration',
            name='wavelength',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='(in Å)If empty uses the value set in the data file.', max_digits=4, null=True),
        ),
    ]
