# Generated by Django 2.0.2 on 2018-02-23 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sans', '0003_auto_20180223_1121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biosansregion',
            name='stitch',
        ),
        migrations.RemoveField(
            model_name='gpsansregion',
            name='stitch',
        ),
    ]
