# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-09 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sans', '0004_auto_20170109_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='biosansconfiguration',
            name='sample_detector_distance',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='(in meters) If empty uses the value set in the data file.', max_digits=5, null=True, verbose_name='Sample Detector Distance (m)'),
        ),
        migrations.AddField(
            model_name='biosansconfiguration',
            name='solid_angle_correction',
            field=models.CharField(choices=[('', 'None'), ('detector_tubes=False, detector_wing=False', 'Regular'), ('detector_tubes=Tubes, detector_wing=False', 'Tubes'), ('detector_tubes=False, detector_wing=True', 'Wing')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='biosansconfiguration',
            name='wavelength',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='If empty uses the value set in the data file.', max_digits=4, null=True, verbose_name='Wavelength (Å)'),
        ),
        migrations.AddField(
            model_name='biosansconfiguration',
            name='wavelength_spread',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='If empty uses the value set in the data file.', max_digits=3, null=True, verbose_name='Wavelength Spread (%)'),
        ),
        migrations.AddField(
            model_name='gpsansconfiguration',
            name='normalization',
            field=models.CharField(choices=[('NoNormalization()', 'None'), ('TimeNormalization()', 'Time'), ('MonitorNormalization()', 'Monitor')], default='MonitorNormalization()', max_length=50),
        ),
        migrations.AddField(
            model_name='gpsansconfiguration',
            name='solid_angle_correction',
            field=models.CharField(choices=[('', 'None'), ('detector_tubes=False, detector_wing=False', 'Regular'), ('detector_tubes=Tubes, detector_wing=False', 'Tubes')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='gpsansconfiguration',
            name='absolute_scale_factor',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='gpsansconfiguration',
            name='sample_detector_distance',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='(in meters) If empty uses the value set in the data file.', max_digits=5, null=True, verbose_name='Sample Detector Distance (m)'),
        ),
        migrations.AlterField(
            model_name='gpsansconfiguration',
            name='wavelength',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='If empty uses the value set in the data file.', max_digits=4, null=True, verbose_name='Wavelength (Å)'),
        ),
        migrations.AlterField(
            model_name='gpsansconfiguration',
            name='wavelength_spread',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='If empty uses the value set in the data file.', max_digits=3, null=True, verbose_name='Wavelength Spread (%)'),
        ),
    ]
