# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 20:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Profile'},
        ),
    ]
