# Generated by Django 2.0.4 on 2018-05-15 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configurationhyspec',
            options={'verbose_name': 'Configuration HYSPEC', 'verbose_name_plural': 'Configurations HYSPEC'},
        ),
        migrations.AlterModelOptions(
            name='maskhyspec',
            options={'verbose_name': 'Mask HYSPEC', 'verbose_name_plural': 'Masks HYSPEC'},
        ),
        migrations.AlterField(
            model_name='maskhyspec',
            name='configuration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='masks', related_query_name='mask', to='configuration.ConfigurationHYSPEC'),
        ),
    ]
