# Generated by Django 2.0.5 on 2018-06-06 17:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configurationbiosans',
            name='user',
        ),
        migrations.RemoveField(
            model_name='configurationgpsans',
            name='user',
        ),
        migrations.RemoveField(
            model_name='configurationhyspec',
            name='user',
        ),
        migrations.AddField(
            model_name='configurationbiosans',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='configurationgpsans',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='configurationhyspec',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
