# Generated by Django 2.0.2 on 2018-03-06 20:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import server.apps.configuration.models.abstract


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0001_initial'),
        ('configuration', '0002_spectometrysnshyspecconfiguration_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpectrometrySnsHyspecConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('wavelength', models.DecimalField(blank=True, decimal_places=2, help_text='If empty uses the value set in the data file.', max_digits=4, null=True, verbose_name='Wavelength (Å)')),
                ('wavelength_spread', models.DecimalField(blank=True, decimal_places=2, help_text='If empty uses the value set in the data file.', max_digits=3, null=True, verbose_name='Wavelength Spread (%)')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spectrometrysnshyspecconfiguration_instruments', related_query_name='spectrometrysnshyspecconfiguration_instrument', to='catalog.Instrument')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spectrometrysnshyspecconfiguration_users', related_query_name='spectrometrysnshyspecconfiguration_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'ordering': ['id'],
            },
            bases=(models.Model, server.apps.configuration.models.abstract.ModelMixin),
        ),
        migrations.RemoveField(
            model_name='spectometrysnshyspecconfiguration',
            name='instrument',
        ),
        migrations.RemoveField(
            model_name='spectometrysnshyspecconfiguration',
            name='user',
        ),
        migrations.DeleteModel(
            name='SpectometrySnsHyspecConfiguration',
        ),
    ]
