# Generated by Django 2.0.2 on 2018-03-06 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0003_auto_20180306_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='spectrometrysnshyspecconfiguration',
            name='configuration_file',
            field=models.CharField(blank=True, help_text='Server side file path', max_length=256),
        ),
    ]
